export const Feilds = [
  "canMintBurn",
  "coinAmt",
  "decimals",
  "holdingTax",
  "holdingTaxBool",
  "holdingTaxInterval",
  "nameType",
  "privacy",
  "secured",
  "txnTax",
  "txnTaxBool",
  "secured",
  "privacy",
];

export const RegistrationTypesList = [
  {
    name: "Business",
    child: [
      "Sole-Proprietorship",
      "Partnership",
      "Corporation",
      "LLC",
      "LLP",
      "Foundation (must be registered and overseen by a notary or lawyer)",
      "Trust",
      "Nonprofit Organization",
      "Charitable Organization (has to be recognized by the local government)",
      "Other (Any legal company incorporated within a country)",
    ],
  },
  { name: "Item", child: [] },
  {
    name: "House",
    child: [
      "Single-Family Home",
      "Duplex",
      "Triplex",
      "Townhouse",
      "Condominium",
      "Mobile Home",
      "Tiny Home",
      "Farm House",
      "Lake House",
      "Beach House",
      "Cabin",
      "Mansion",
      "Other (Any building which houses one to three families; Single-to-Triplex. Any building bigger is not a home and needs to be signed up under Real Estate)",
    ],
  },
  {
    name: "Spacecraft",
    child: [
      "Spaceship",
      "Space Station",
      "Satellite",
      "Rocket",
      "Asteroid",
      "Comet",
      "Commercial Vehicle",
      "Other (Anything that can reach and/or traverse space)",
    ],
  },
  {
    name: "Aeronautical Vehicle",
    child: [
      "Plane",
      "Jet",
      "Helicopter",
      "UAV",
      "Flying Car",
      "Hot Air Balloon",
      "Weather Balloon",
      "Blimp",
      "Glider",
      "Paramotor",
      "Commercial Vehicle",
      "Other (Anything that can fly in the air)",
    ],
  },
  {
    name: "Waterborne Vessel",
    child: [
      "Boat",
      "Sail Boat",
      "Jet Ski",
      "Cargo Ship",
      "Fishing Vessel",
      "Submarine",
      "Racing Boat",
      "Yacht",
      "Cruiseliner",
      "Commercial Vehicle",
      "Other (Anything that traverses or submerses in a body of water)",
    ],
  },

  {
    name: "Automobile",
    child: [
      "Car",
      "Sports Car",
      "Jeep",
      "Van",
      "Truck",
      "RV",
      "4 wheeler",
      "3 wheeler",
      "Motorcycle",
      "Snowmobile",
      "Taxi",
      "Limousine",
      "Food Truck",
      "Racing Car",
      "Hovercraft",
      "Commercial Vehicle",
      "Other (Anything that traverses the land)",
    ],
  },
  {
    name: "Real Estate",
    child: [
      "Land",
      "Farm",
      "Factory",
      "Laboratory",
      "Workshop",
      "Office",
      "Education Institution",
      "Library",
      "Church",
      "Museum",
      "Memorial",
      "Bar",
      "Winery",
      "Casino",
      "Public Venue",
      "Gym",
      "Park",
      "Wildlife Preserve",
      "Nursery",
      "Dentistry",
      "Veterinary",
      "Hospital",
      "Medical Practice",
      "Pharmacy",
      "Grocery",
      "Storage Facility",
      "Warehouse",
      "Bank",
      "Tower",
      "Skyscraper",
      "Hotel",
      "Apartment",
      "Shopping Mall",
      "Fast Food Joint",
      "Restaurant",
      "Theater",
      "Retail Store",
      "Mine/Quarry",
      "Refinery",
      "Fuel Depot",
      "Transportation Hub",
      "Airport",
      "Seaport",
      "Commercial Property",
      "Other (Any land with or without structures on it that is not a house)",
    ],
  },
];
